# Generated by Django 3.1.4 on 2020-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.FloatField()),
                ('designation', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='employee_images/')),
                ('file', models.FileField(upload_to='employee_docs/')),
            ],
        ),
    ]
