def math_fun(a, b=10):
    print("addition is", a+b)
    print("subraction is", a-b)
    print("multiplication is", a*b)
    print("divition is", a/b)
# math_fun()
print("---------------------------------------------------------")
math_fun(1000)
print("---------------------------------------------------------")
# math_fun(1000)