# Generated by Django 3.1 on 2020-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('ContactNo', models.IntegerField()),
                ('Registered_Course', models.CharField(max_length=50)),
                ('Validity', models.DateField(null=True)),
            ],
        ),
    ]
