# Generated by Django 3.1.4 on 2020-12-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('designation', models.CharField(max_length=50)),
                ('contactno', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
